name: StaffChat
version: '${project.version}'
main: bananablu.staffchat.StaffChat
api-version: 1.19
authors: [ _Banana_Blu_ ]
description: A simple staffchat plugin.
commands:
  staffchat:
    aliases: [sc]
  staffchatoggle:
    aliases: [sctoggle]
  staffchatreload:
    aliases: [screload]